# Generated by Django 3.1.2 on 2020-10-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServedDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=260, verbose_name='Directory Path')),
                ('recursive', models.BooleanField(default=False, verbose_name='Files Are Matched Recursively')),
                ('regex_pattern', models.CharField(default=None, max_length=100, verbose_name='RegEx Matching Pattern')),
                ('regex', models.BooleanField(default=False, verbose_name='Directory RegEx Option')),
                ('match_filename', models.BooleanField(default=True, verbose_name='RegEx Matches Against Filename')),
            ],
        ),
    ]
