# Generated by Django 3.1.2 on 2020-11-01 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20201031_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300, verbose_name='Full Filepath')),
                ('filename', models.CharField(max_length=160, verbose_name='Filename')),
                ('mediatype', models.CharField(max_length=30, verbose_name='Mediatype')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='viewer.serveddirectory')),
            ],
        ),
    ]
