# Generated by Django 3.1.2 on 2020-11-01 01:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveddirectory',
            name='known_subdirectories',
            field=jsonfield.fields.JSONField(default=[], verbose_name='Tracked Subdirectories JSON'),
        ),
    ]
