# Generated by Django 3.1.2 on 2020-11-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_serveddirectory_known_subdirectories'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='thumbnail',
            field=models.CharField(default=None, max_length=160, null=True, verbose_name='Thumbnail Filename'),
        ),
    ]
