# Generated by Django 3.1.2 on 2020-11-04 01:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_file_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='fileLastModified',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='initialCreation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='lastModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='lastRefreshed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serveddirectory',
            name='initialCreation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serveddirectory',
            name='lastModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serveddirectory',
            name='lastRefreshed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='file',
            name='resolution',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='viewer.imageresolution'),
        ),
        migrations.AddField(
            model_name='file',
            name='thumbnailResolution',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_file', to='viewer.imageresolution'),
        ),
    ]
