# Generated by Django 3.1.2 on 2020-11-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20201103_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresolution',
            name='x',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imageresolution',
            name='y',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
